/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const UploadIndexLazyImport = createFileRoute('/upload/')()
const TranslateIndexLazyImport = createFileRoute('/translate/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const UploadIndexLazyRoute = UploadIndexLazyImport.update({
  path: '/upload/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/upload/index.lazy').then((d) => d.Route))

const TranslateIndexLazyRoute = TranslateIndexLazyImport.update({
  path: '/translate/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/translate/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/translate/': {
      id: '/translate/'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/upload/': {
      id: '/upload/'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  TranslateIndexLazyRoute,
  UploadIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/translate/",
        "/upload/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/translate/": {
      "filePath": "translate/index.lazy.tsx"
    },
    "/upload/": {
      "filePath": "upload/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
